stages:
  - build
  - benchmark

build:gitinfo:release:
  stage: build
  image: rust:1.74.1-bullseye
  before_script:
    # - apt install cmake
    - rustc -V
    - cargo --version
  script:
    - cargo build --verbose --release --bin gitinfo
  artifacts:
    # untracked: false
    # when: on_success
    # access: all
    expire_in: "30 days"
    paths:
      - "target/release/gitinfo"

bench-binocular:
  stage:
    benchmark
  needs:
    - job: build:gitinfo:release
      artifacts: true
  image: debian:bullseye
  before_script:
    - apt-get install git hyperfine
  script:
    - git clone --no-checkout https://github.com/INSO-TUWien/Binocular.git
    - cd Binocular
    - git checkout develop
    - git rev-list --count HEAD
    - git rev-list --count --no-merges HEAD
    - ls -lah .