stages:
  - build
  - benchmark

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PY_VER: "python:3.13.0-alpine3.19"
  RUST_VER: "rust:1.81.0-alpine3.19"

.before_script:
  before_script:
    - python --version # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

.default_python:
  extends: .before_script
  image: $PY_VER
  cache:
    paths:
      - .cache/pip
      - .venv/

build:gitinfo:release:
  stage: build
  image: $RUST_VER
  cache:
    - key:
        files:
          - Cargo.lock
      fallback_keys:
        - cache-$CI_DEFAULT_BRANCH
        - cache-default
      paths:
        - ./target
  before_script:
    - apk add make cmake gcc g++
    - rustc -V
    - cargo --version
  script:
    - cargo build --verbose --release --bin gitinfo
  artifacts:
    # untracked: false
    # when: on_success
    # access: all
    expire_in: "60 days"
    paths:
      - "target/release/gitinfo"

fork-join:rust:
  stage: benchmark
  when: manual
  image: alpine:3.18
  script:
    - echo "OK"

fork-join:python:
  extends: "fork-join:rust"

.benchmark-base:python:
  extends: .default_python
  stage:
    benchmark
  needs:
    - job: "fork-join:python"
  image: $PY_VER
  variables:
  before_script:
    - apk add git hyperfine bash libgit2 make cmake gcc g++
    - pip install pyrepositoryminer --index-url https://gitlab-ci-token:${CI_JOB_TOKEN}@reset.inso.tuwien.ac.at/repo/api/v4/projects/4273/packages/pypi/simple
    - pyrepositoryminer --help
    - nproc --all
  script:
    - echo ${URL}, ${TARGET}
    - git clone --no-checkout ${URL} ${TARGET}
    - cd ${TARGET}
    - git rev-list --count HEAD
    - git rev-list --count --no-merges HEAD
    - cd ..
    - pyrepositoryminer branch --no-local --remote ${TARGET} | grep -v -E '^origin/HEAD$' > branches.txt
    - hyperfine --show-output --warmup ${WARMUPS} --runs ${RUNS} --export-json hyperfine.pyrepositoryminer.${TARGET}.json --export-csv hyperfine.pyrepositoryminer.${TARGET}.csv --parameter-list repo ${TARGET} 'cat branches.txt | pyrepositoryminer commits --no-simplify-first-parent --no-drop-duplicates {repo} | wc -l'
    - cat branches.txt | pyrepositoryminer commits --no-simplify-first-parent --no-drop-duplicates ${TARGET} | wc -l
  artifacts:
    # untracked: false
    when: always
    # access: all
    expire_in: "30 days"
    paths:
      - "branches.txt"
      - "hyperfine.pyrepositoryminer.${TARGET}.json"
      - "hyperfine.pyrepositoryminer.${TARGET}.csv"


.benchmark-base:
  stage:
    benchmark
  timeout: 5h
  needs:
    - job: "build:gitinfo:release"
      artifacts: true
    - job: "fork-join:rust"
  image: alpine:3.18
  before_script:
    - apk add git hyperfine bash
    - nproc --all
  variables:
  script:
    - echo ${URL}, ${TARGET}
    - git clone --no-checkout ${URL} ${TARGET}
    - cd ${TARGET}
    - git rev-list --count HEAD
    - git rev-list --count --no-merges HEAD
    - cd ..
    - ls -lah .
    - ls -lah ./scripts
    - ./target/release/gitinfo --help
    - hyperfine --warmup ${WARMUPS} --runs ${RUNS} --export-json hyperfine.gitinfo.${TARGET}.json --export-csv hyperfine.gitinfo.${TARGET}.csv --parameter-list repo ${TARGET} --parameter-list workers 1,2,3,4,5,6,7,8 --parameter-list algorithm histogram,myers,myers-minimal './target/release/gitinfo diff --git-dir {repo} --threads {workers} --algorithm {algorithm}'
  artifacts:
    # untracked: false
    when: always
    # access: all
    expire_in: "30 days"
    paths:
      - "hyperfine.gitinfo.${TARGET}.json"
      - "hyperfine.gitinfo.${TARGET}.csv"


############################## PYTHON BENCHMARKS ##############################
bench-binocular:python:
  extends: .benchmark-base:python
  variables:
    URL: https://github.com/INSO-TUWien/Binocular.git
    TARGET: binocular
    WARMUPS: 1
    RUNS: 10

bench-dubbo:python: # 7492 commits
  extends: .benchmark-base:python
  variables:
    URL: https://github.com/apache/dubbo.git
    TARGET: dubbo
    WARMUPS: 1
    RUNS: 10

bench-pandas:python: # 34933 commits
  extends: .benchmark-base:python
  variables:
    URL: https://github.com/pandas-dev/pandas.git
    TARGET: pandas
    WARMUPS: 1
    RUNS: 10

############################## RUST BENCHMARKS ##############################
bench-binocular: # 1724 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/INSO-TUWien/Binocular.git
    TARGET: binocular
    WARMUPS: 1
    RUNS: 10

bench-dubbo: # 7492 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/apache/dubbo.git
    TARGET: dubbo
    WARMUPS: 1
    RUNS: 5
    
bench-click: # 2443 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/pallets/click.git
    TARGET: click
    WARMUPS: 1
    RUNS: 10

bench-jinja: # 2794 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/pallets/jinja.git
    TARGET: jinja
    WARMUPS: 1
    RUNS: 10

bench-spring-ai: # 642 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/spring-projects/spring-ai.git
    TARGET: spring-ai
    WARMUPS: 1
    RUNS: 15

bench-spring-graphql: # 1294 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/spring-projects/spring-graphql.git
    TARGET: spring-graphql
    WARMUPS: 1
    RUNS: 10

bench-spring-kafka: # 2348 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/spring-projects/spring-kafka.git
    TARGET: spring-kafka
    WARMUPS: 1
    RUNS: 5

bench-spring-data-jpa: # 2143 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/spring-projects/spring-data-jpa.git
    TARGET: spring-data-jpa
    WARMUPS: 1
    RUNS: 5

bench-spring-petclinic: # 893 commits
  extends: .benchmark-base
  variables:
    URL: https://github.com/spring-projects/spring-petclinic.git
    TARGET: spring-petclinic
    WARMUPS: 1
    RUNS: 15