[package]
name = "diff"
version = "0.1.0"
edition = "2021"
autotests = false
include = ["src/**/*"]

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
crossbeam-channel = "0.5.13"
gix = { workspace = true, features = ["max-performance-safe", "blob-diff", "revision", "mailmap", ] }
shared = { path = "../shared" }
render = { path = "../render" }
serde_json = "1.0.128"

log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }