name: ci
run-name: ci
on: [push]

jobs:
  pure-rust-build:
    runs-on: ubuntu-latest-slim
    container: rust:1-alpine3.21
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - name: Install nodejs
        run: |
          apk update
          apk add --no-cache nodejs
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
      - name: Prerequisites
        run: |
          prerequisites=(
            make
            cmake
            gcc
            g++
            bash
            git
          )
          apk update
          apk add "${prerequisites[@]}"
        shell: bash
