name: ci
run-name: ci
on: [push]

jobs:
  pure-rust-build:
    runs-on: ubuntu-latest-slim
    container:
      image: rust-ci:1-alpine3.21
      volumes:
        - /cache:/opt/hostedtoolcache # this is where Runner store their cache default
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
      - name: "📋 Print command version"
        run: |
          rustc -V
          cargo --version
          bash --version
          /usr/bin/env bash --version
          git --version
          tar --version
      - name: "⚡ Cache"
        uses: Swatinem/rust-cache@v2
      - name: "🔨 Build executable (dev)"
        run: cargo build --profile=ci-dev --bin gitinfo
