name: ci
run-name: ci
on: [push]

jobs:
  pure-rust-build:
    runs-on: ubuntu-latest-slim
    container: rust:1-alpine3.21
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - name: Install nodejs
        run: |
          apk update
          apk add --no-cache nodejs
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
      - name: Prerequisites
        run: |
          prerequisites=(
            make
            cmake
            gcc
            g++
            bash
            git
            musl-dev
          )
          apk update
          apk add --no-cache "${prerequisites[@]}"
          rustc -V >> $GITHUB_OUTPUT
          cargo --version >> $GITHUB_OUTPUT
          bash --version >> $GITHUB_OUTPUT
          /usr/bin/env bash --version >> $GITHUB_OUTPUT
          git --version >> $GITHUB_OUTPUT
        shell: ash
      - name: "Build executable (dev)"
        run: cargo build --profile=ci-dev --bin gitinfo
