name: ci
run-name: ci
on: [push]

jobs:
  pure-rust-build:
    runs-on: ubuntu-latest-slim
    container:
      image: rust:1-alpine3.21
      volumes:
        - /cache:/opt/hostedtoolcache # this is where Runner store their cache default
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - name: Install nodejs
        run: |
          apk update
          apk add --no-cache nodejs
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal
      - name: "⚡ Cache"
        uses: Swatinem/rust-cache@v2
      - name: "📋 Prerequisites"
        run: |
          apk update
          apk add --no-cache make cmake gcc g++ bash git musl-dev tar
          rustc -V
          cargo --version
          bash --version
          /usr/bin/env bash --version
          git --version
          tar --version
      - name: "🔨 Build executable (dev)"
        run: cargo build --profile=ci-dev --bin gitinfo
