name: ci
run-name: ci
on: [push]

jobs:
  pure-rust-build:
    runs-on: ubuntu-latest-slim
    container: rust:1-alpine3.21
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - name: Install nodejs
        run: |
          apk update
          apk add --no-cache nodejs
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
      - name: "⚡ Cache"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: "📋 Prerequisites"
        run: |
          prerequisites=(
            make
            cmake
            gcc
            g++
            bash
            git
            musl-dev
          )
          apk update
          apk add --no-cache "${prerequisites[@]}"
          rustc -V
          cargo --version
          bash --version
          /usr/bin/env bash --version
          git --version
      - name: "🔨 Build executable (dev)"
        run: cargo build --profile=ci-dev --bin gitinfo
