[package]
name = "python"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Stöger <manuel.stoeger@inso-world.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# The name of the native library. This is the name which will be used in Python to import the
# library (i.e. `import string_sum`). If you change this, you must also change the name of the
# `#[pymodule]` in `src/lib.rs`.
name = "gix_pyo3"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
cartography-diff = { path = "../diff" }
commits = { path = "../commits" }
cli = { path = "../cli" }
render = { path = "../render" }

gix = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }

csv = "1.3.0"
