[package]
name = "shared"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Stöger <manuel.stoeger@inso-world.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gix = { workspace = true }
env_logger = { workspace = true }
chrono = "0.4.38"

[lib]
doctest = false