name: ci

on:
  push:
    branches:
      - main
      - 'run-ci/**'
      - 'gix/main'
      - '**/run-ci/**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: '1'

jobs:
#  msrv:
#    name: cargo check MSRV
#
#    strategy:
#      matrix:
#        os:
#          - windows-2022
#          - ubuntu-latest
#
#    runs-on: ${{ matrix.os }}
#
#    defaults:
#      run:
#        shell: bash  # Use `bash` even in the Windows job.
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: extractions/setup-just@v3
#      - name: Read the MSRV
#        run: |
#          msrv="$(just msrv)"
#          tee -a "$GITHUB_ENV" <<<"MSRV=$msrv"
#      - name: Set up MSRV and nightly toolchains
#        run: |
#          rustup toolchain install "$MSRV" nightly --profile minimal --no-self-update
#      - name: Downgrade locked dependencies to lowest allowed versions
#        run: |
#          # TODO(msrv): Use `cargo update --minimal-versions` when `--minimal-versions` is available.
#          cargo +nightly update -Zminimal-versions
#      - name: Run some `cargo build` commands on `gix`
#        run: just check-rust-version "$MSRV"
#
#  msrv-badge:
#    name: Check MSRV badge
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: extractions/setup-just@v3
#      - name: Ensure we start out clean
#        run: git diff --exit-code
#      - name: Regenerate the MSRV badge
#        run: just msrv-badge
#      - name: Check for changes
#        run: git diff --exit-code

  pure-rust-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container-arch: amd64
            runner-arch: amd64
            runner-os: ubuntu-latest
            host-triple: x86_64-unknown-linux-gnu
            file-ending: so
          - container-arch: arm64
            runner-arch: arm64
            runner-os: macos-latest
            host-triple: aarch64-apple-darwin
            file-ending: dylib
          - container-arch: x86_64
            runner-arch: x86_64
            runner-os: macos-latest
            host-triple: x86_64-apple-darwin
            file-ending: dylib
#          - container-arch: arm64
#            runner-arch: arm64
#            runner-os: ubuntu-latest
#            host-triple: aarch64-unknown-linux-gnu
#          - container-arch: arm32v7
#            runner-arch: arm64
#            runner-os: ubuntu-latest
#            host-triple: armv7-unknown-linux-gnueabihf
    runs-on: ${{ matrix.runner-os }}
    container: ${{ matrix.container-arch }}/debian:stable-slim

    steps:
      - name: Install Docker
        if: startsWith(matrix.os, 'macos')
        - run: |
            brew install docker
            colima start
            docker run -e "ACCEPT_EULA=Y"
      - uses: actions/checkout@v4
      - name: Prerequisites
        run: |
          prerequisites=(
            ca-certificates
            curl
            gcc  # rustc calls gcc to invoke the linker.
            libc-dev  # rustc, in the toolchain we are using, dynamically links to the system libc.
          )
          dpkg --add-architecture ${{ matrix.runner-arch }}
          apt-get update
          apt-get install --no-install-recommends -y -- "${prerequisites[@]}"
        shell: bash  # This step needs `bash`, and the default in container jobs is `sh`.
      - name: Verify that we are in an environment with limited dev tools
        run: |
          set -x
          for package in cmake g++ libssl-dev make pkgconf pkg-config; do
            if dpkg-query --status -- "$package"; then
              exit 1
            fi
          done
          for cmd in cmake g++ make pkgconf pkg-config; do
            if command -v -- "$cmd"; then
              exit 1
            fi
          done
      - name: Install Rust via Rustup
        run: |
          # Specify toolchain to avoid possible misdetection based on the 64-bit running kernel.
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
            sh -s -- -y --default-host ${{ matrix.host-triple }} --profile minimal
      - name: Add Rust tools to path
        run: echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"
      - uses: Swatinem/rust-cache@v2
      - name: crates without feature toggles
        shell: bash
        run: |
          crates=(
            binocular-ffi
          )
          set +x
          for crate in "${crates[@]}"; do
            cargo build --release -p "$crate" --target ${{ matrix.host-triple }}
          done
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.host-triple }}
          path: target/${{ matrix.host-triple }}/release/libbinocular_ffi.${{ matrix.file-ending }}

#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dtolnay/rust-toolchain@stable
#      - uses: Swatinem/rust-cache@v2
#      - name: Setup dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y --no-install-recommends liblzma-dev
#      - uses: extractions/setup-just@v3
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: nextest
#      - name: test
#        env:
#          GIX_TEST_IGNORE_ARCHIVES: '1'
#        run: just ci-test
#
#  test-journey:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dtolnay/rust-toolchain@stable
#      - uses: Swatinem/rust-cache@v2
#      - uses: extractions/setup-just@v3
#      - name: Run journey tests
#        run: just ci-journey-tests
#
#  test-fast:
#    strategy:
#      matrix:
#        os:
#          - windows-latest
#          - macos-latest
#          - ubuntu-latest
#          - ubuntu-24.04-arm
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dtolnay/rust-toolchain@stable
#      - uses: Swatinem/rust-cache@v2
#      - name: cargo check default features
#        if: startsWith(matrix.os, 'windows')
#        run: cargo check --workspace --bins --examples
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: nextest
#      - name: Test (nextest)
#        env:
#          GIX_TEST_CREATE_ARCHIVES_EVEN_ON_CI: '1'
#        run: cargo nextest run --workspace --no-fail-fast
#      - name: Check that tracked archives are up to date
#        run: git diff --exit-code  # If this fails, the fix is usually to commit a regenerated archive.

#  test-fixtures-windows:
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dtolnay/rust-toolchain@stable
#      - uses: Swatinem/rust-cache@v2
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: nextest
#      - name: Test (nextest)
#        id: nextest
#        env:
#          GIX_TEST_IGNORE_ARCHIVES: '1'
#        run: cargo nextest --profile=with-xml run --workspace --no-fail-fast
#        continue-on-error: true
#      - name: Check for errors
#        run: |
#          [xml]$junit_xml = Get-Content -Path 'target/nextest/with-xml/junit.xml'
#          if ($junit_xml.testsuites.errors -ne 0) { exit 1 }
#      - name: Collect actual failures
#        run: |
#          [xml]$junit_xml = Get-Content -Path 'target/nextest/with-xml/junit.xml'
#
#          $actual_failures = $junit_xml.SelectNodes("//testcase[failure]") |
#            ForEach-Object { "$($_.classname) $($_.name)" } |
#            Sort-Object
#
#          Write-Output $actual_failures
#          Set-Content -Path 'actual-failures.txt' -Value $actual_failures
#      - name: Compare expected and actual failures
#        run: |
#          # Fail on any differences, even unexpectedly passing tests, so they can be investigated.
#          git --no-pager diff --no-index --exit-code --unified=1000000 --color=always -- `
#            etc/test-fixtures-windows-expected-failures-see-issue-1358.txt actual-failures.txt

#  test-32bit:
#    strategy:
#      matrix:
#        container-arch: [ i386, arm32v7 ]
#        include:
#          - container-arch: i386
#            runner-arch: amd64
#            runner-os: ubuntu-latest
#            host-triple: i686-unknown-linux-gnu
#          - container-arch: arm32v7
#            runner-arch: arm64
#            runner-os: ubuntu-24.04-arm
#            host-triple: armv7-unknown-linux-gnueabihf
#
#    runs-on: ${{ matrix.runner-os }}
#
#    container: ${{ matrix.container-arch }}/debian:stable-slim
#
#    steps:
#      - name: Prerequisites
#        run: |
#          prerequisites=(
#            build-essential
#            ca-certificates
#            cmake
#            curl
#            git
#            jq
#            libssl-dev
#            libstdc++6:${{ matrix.runner-arch }}  # To support external 64-bit Node.js for actions.
#            pkgconf
#          )
#          dpkg --add-architecture ${{ matrix.runner-arch }}
#          apt-get update
#          apt-get install --no-install-recommends -y -- "${prerequisites[@]}"
#        shell: bash  # This step needs `bash`, and the default in container jobs is `sh`.
#      - uses: actions/checkout@v4
#      - name: Install Rust via Rustup
#        run: |
#          # Specify toolchain to avoid possible misdetection based on the 64-bit running kernel.
#          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
#            sh -s -- -y --default-host ${{ matrix.host-triple }} --profile minimal
#      - name: Add Rust tools to path
#        run: echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"
#      - uses: Swatinem/rust-cache@v2
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: nextest
#      - name: Make `system` scope nonempty for "GitInstallation" tests
#        run: git config --system gitoxide.imaginary.arbitraryVariable arbitraryValue
#      - name: Test (nextest)
#        env:
#          GIX_TEST_IGNORE_ARCHIVES: '1'
#        run: cargo nextest run --workspace --no-fail-fast

#  test-32bit-windows-size:
#    runs-on: windows-latest
#
#    env:
#      TARGET: i686-pc-windows-msvc
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dtolnay/rust-toolchain@stable
#        with:
#          targets: ${{ env.TARGET }}
#      - uses: Swatinem/rust-cache@v2
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: nextest
#      - name: Test (nextest)
#        run: cargo nextest run --target $env:TARGET --workspace --no-fail-fast size

#  test-wasm32:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
##        target: [ wasm32-unknown-unknown, wasm32-wasip1, wasm32-wasip2 ]
#        target: [ wasm32-wasip2 ]
#
#    env:
#      TARGET: ${{ matrix.target }}
#
#    steps:
#      - uses: actions/checkout@v4
##      - uses: dtolnay/rust-toolchain@nightly
##        with:
##          targets: ${{ env.TARGET }}
#      - name: Install Rust
#        run: |
#          rustup update nightly
#          rustup default nightly
#          rustup target add "$TARGET"
#      - uses: Swatinem/rust-cache@v2
#      - uses: taiki-e/install-action@v2
#        with:
#          tool: nextest
#      - name: Test (nextest)
#        run: cargo +nightly nextest run --no-default-features --target $TARGET --package gix --no-fail-fast size


#  wasm:
#    name: WebAssembly
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        target: [ wasm32-unknown-unknown, wasm32-wasip1, wasm32-wasip2 ]
#
#    env:
#      TARGET: ${{ matrix.target }}
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Install Rust
#        run: |
#          rustup update nightly
#          rustup default nightly
#          rustup target add "$TARGET"
#      - uses: Swatinem/rust-cache@v2
#      - name: 'WASI only: crates without feature toggle'
#        if: endsWith(matrix.target, '-wasi')
#        run: |
#          set +x
#          for crate in gix-sec; do
#            cargo build -p "$crate" --target "$TARGET"
#          done
#      - name: crates without feature toggles
#        run: |
#          crates=(
#            gix-actor
#            gix-attributes
#            gix-bitmap
#            gix-chunk
#            gix-command
#            gix-commitgraph
#            gix-config-value
#            gix-date
#            gix-glob
#            gix-hash
#            gix-hashtable
#            gix-mailmap
#            gix-object
#            gix-packetline
#            gix-path
#            gix-pathspec
#            gix-prompt
#            gix-quote
#            gix-refspec
#            gix-revision
#            gix-traverse
#            gix-url
#            gix-validate
#          )
#          set +x
#          for crate in "${crates[@]}"; do
#            cargo build -p "$crate" --target "$TARGET"
#          done
#      - name: features of gix-features
#        run: |
#          set +x
#          for feature in progress parallel io-pipe crc32 zlib cache-efficiency-debug; do
#            cargo build -p gix-features --features "$feature" --target "$TARGET"
#          done
#      - name: crates with 'wasm' feature
#        run: |
#          set +x
#          for crate in gix-pack; do
#            cargo build -p "$crate" --features wasm --target "$TARGET"
#          done
#      - name: gix-pack with all features (including wasm)
#        run: cargo build -p gix-pack --all-features --target "$TARGET"